### ISSUE TITLE
fuzzing: negation can result in overflow inside TextView::svtoi

### ISSUE THREAD

**Issue by shukitchan** [apache/trafficserver#10934]
Fuzzing finds out a potential problem in TextView. 

The line in question is https://github.com/apache/trafficserver/blob/master/lib/swoc/src/TextView.cc#L64

zret = -zret 

So LONG_MIN is -9223372036854775808 and LONG_MAX is 9223372036854775807
If zret is LONG_MIN, then -zret will result in overflow and it can result in an undefined behavior depending on the system. 

The fuzzing finding for this problem is here - https://oss-fuzz.com/testcase-detail/5196561539530752
You can check out the details of this particular finding from ubsan here (under Unary Negation section) - https://wiki.sei.cmu.edu/confluence/display/c/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow

**Comment by shukitchan** [comment]
@SolidWallOfCode , can you give some advice here?

**Comment by SolidWallOfCode** [comment]
Fixed in [this commit](https://github.com/SolidWallOfCode/libswoc/commit/8e90f48b6718d84cf6dde5b4f20427bd4382822f). There is other IP and `Errata` related work ongoing, when these are done there will be a new release for ATS (libswoc 1.5.9).

**Comment by shukitchan** [comment]
Problem is still there. I will take a look and attempt a fix next week
