### ISSUE TITLE
Memory Leak - traffic_ctl config reload

### ISSUE THREAD

**Issue by alxtv** [apache/trafficserver#4562]
Hi,

I have noticed that the trafficserver's memory usage is increasing with each config reload. After each config reload it's allocating ~200MB RAM until the system has free memory and then dies (oom killer or trafficserver cannot allocate memory). There are around 7700 remap rules and 1800 SSL certificates on the server if that matters.

Tested on - Apache Traffic Server - traffic_server - 7.1.5 - (build # 110507 on Nov  5 2018 at 07:03:44)
executing - touch /etc/trafficserver/remap.config && touch /etc/trafficserver/ssl_multicert.config && traffic_ctl config reload
But older version 7.1.4 has the same issue.
Edit:
I have noticed that it's allocating more memory while reloading the ssl_multicert.config

Memory Dump
[ts-start.txt](https://github.com/apache/trafficserver/files/2552923/ts-start.txt)
[ts-after-few-reloads.txt](https://github.com/apache/trafficserver/files/2552924/ts-after-few-reloads.txt)

edit 2:
Even with empty remap.config and no plugins activated,  touch /etc/trafficserver/ssl_multicert.config && traffic_ctl config reload is increasing the memory usage.

Edit 3:
Empty ssl_multicert.config and the memory leak is completely gone.

**Comment by randall** [comment]
I just went through and found/fixed a number of leaks related to reloading but nothing really with ssl_multicert. There was a fix for when a cert didn't have an OCSP URL.

Which version of 7.1.5 were you using here?

Any more details about the contents of ssl_multicert.config? What's the typical config line look like? Just trying to get an idea of the features/codepaths used here.

**Comment by alxtv** [comment]
The configuration of ssl_multicert.config is very simple it's like:
ssl_cert_name=/home/ssl/domain1.com.cert ssl_key_name=/home/ssl/domain1.com.key ssl_ca_name=/home/ssl/domain1.com.ca
ssl_cert_name=/home/ssl/domain2.com.cert ssl_key_name=/home/ssl/domain2.com.key ssl_ca_name=/home/ssl/domain2.com.ca
ssl_cert_name=/home/ssl/domain3.com.cert ssl_key_name=/home/ssl/domain3.com.key ssl_ca_name=/home/ssl/domain3.com.ca
ssl_cert_name=/home/ssl/domain4.com.cert ssl_key_name=/home/ssl/domain4.com.key ssl_ca_name=/home/ssl/domain4.com.ca
ssl_cert_name=/home/ssl/domain5.com.cert ssl_key_name=/home/ssl/domain5.com.key ssl_ca_name=/home/ssl/domain5.com.ca
.............
ssl_cert_name=/home/ssl/domain1900.com.cert ssl_key_name=/home/ssl/domain1900.com.key ssl_ca_name=/home/ssl/domain1900.com.ca
............
OCSP is deactivated and all the configuration is almost default. Nothing changed especially for the SSLs.

Source downloaded on 5th Nov from branch 7.1.x so it should include your memory leak fixes.

I have tried with older version 5.3.0 (I think) got from epel repo for CentOS 7 but still has the same issue. There might be also a memory leak while reloading the remap.config but leaking less memory than the ssl_multicert.config. Will try that later.

**Comment by randall** [comment]
That would explain why I don't see similar leaks. I run with OpenSSL 1.1.x (currently 1.1.0i)

**Comment by alxtv** [comment]
Definitely the leak was caused by the OpenSSL. Running for 24h on multiple instances and haven't noticed any memory leaks. I am not sure what's the case with the CentOS openssl but seems very strange.

**Comment by zwoop** [comment]
Can we close this ?

**Comment by alxtv** [comment]
Yes.

**Comment by alxtv** [comment]
Hello again,

I made a test with clear default ATS installation (and configuration). I have added 100k random simple remap rules (map https://domain.com/ https://127.0.2.54/ - nothing else), no plugins, no ssl certificates.
After starting ATS, it allocates ~1G RAM, after touching remap.config and running "traffic_ctl config reload" it allocates additional 1GB ram, and more ~300MB on the second "traffic_ctl config reload". After that I am reloading the config with "traffic_ctl config reload" more than 10 times but it doesn't allocate any more memory.

I have noticed that while starting the server it executes "mmap(NULL, 270336, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1b2337d000" - 1664 times (with different memory addresses of course) while loading the remap.config (100k remap rules). That's about ~430MB memory from total 1GB which is probably okay for the amount of remap rules.

When I touch the remap.config and run "traffic_ctl config reload", the ET_TASK thread executes "mprotect(0x7f1afe7aa000, 4096, PROT_READ|PROT_WRITE) = 0"  - 58133 times - (~230MB) and "mprotect(0x7f1b0227b000, 266240, PROT_READ|PROT_WRITE) = 0" - 3092 times - (~785MB) which is exactly the amount ATS allocates after first "traffic_ctl config reload".

For the second touch of remap.config and running "traffic_ctl config reload", the ET_TASK thread executes "mprotect(0x7f1afe7aa000, 4096, PROT_READ|PROT_WRITE) = 0" -  61371 times - (~240MB) which is not exactly what I mentioned earlier (~300MB) but I am not getting the exact values in bytes so it should be the same.

When I touch the remap.config and run "traffic_ctl config reload" for the third time, the ET_TASK thread is not executing mprotect or mmap anymore, and no more memory is allocated. I have tried to touch and reload the config many times in a row but no more memory is being allocated.

This was tested on latest version from the master branch on Linux 4.18.0-13-generic #14-Ubuntu SMP 2018 x86_64 and confirmed on CentOS 7 with ATS version 7.1.5.

I am not sure why it's working this way and if it's okay or not. It just looks strange for me.

I am attaching the strace logs of all ATS threads in case anyone wants to see them.

[strace.zip](https://github.com/apache/trafficserver/files/2745767/strace.zip)

Let me know if you need any additional information on the case.

**Comment by bryancall** [comment]
@jamesjbarlow Can you please have someone take a look at this?

**Comment by duke8253** [comment]
I've tracked the problem down, it was fixed in #3297. 
@bryancall let me know if you want me to cherry pick it to 7.1.x, or you want to do it.

**Comment by yaworpetrov** [comment]
@duke8253 we've tested today with the very last updates from master the and issue is still there, initial load of 653MB, after 2 config reloads jumped to 1.3GB of memory and after that it stops making memory peaks raise but continues to raise it by little with every following reload. Thus if the trafficserver has loaded initially 2GBs in the memory it would jump almost double over that within the first two reloads.

As for the dirty fix that you provided:
- master branch build: crashed the server (I adapted the code to the existing)
- 7.1.x branch build: same bug occurs as described above

Any other suggestions where we should be searching for the problem?

**Comment by duke8253** [comment]
@yaworpetrov master branch already has the proper code, you don't need to do anything. As far as I know, the double amount is kind of expected for now, I can however dig a bit deeper to see if those can be freed up. For the 7.1.x branch, the dirty fix shouldn't crash the server, could you upload a stack trace of your crash?

**Comment by yaworpetrov** [comment]
@duke8253 by the words "the same bug occurs" I recon the memory doubling issue, not the server crash. The server crash occurred when I added the missing line from your code to the master branch, because I decided to give it a try since it wouldn't hurt, no matter that I saw that it already has much of your fix already placed there. Forgot to mention that with the master branch without any editing the memory doubling issue remains.

**Comment by duke8253** [comment]
I'm not sure if @zwoop meant to have the memory double with his PR #3297, since we were actually talking about config reloading failing and fall back to an older config, i.e. we need to hold both old and new values at the same time so we have something to fall back to.

**Comment by zwoop** [comment]
All versions of ATS holds at least two copies at reload. The changes on master makes us hold the old version only until not needed any more, whereas before it’d hold the old copies for an hour I think.

**Comment by alxtv** [comment]
OpenSSL definitely plays huge role in the size of allocated memory for ssl certificates. I've repeated the same test but this time compiled ATS with custom SSL (not default coming with OS) openssl-1.1.1g.

40000 pem files:
Starting with 530.1m
Second touch and config reload: 1.0GB
Third touch and config reload: 1.5GB
Fourth touch and config reload: 2.0GB
Fifth+ touch and config reload: 2.5GB - remain constant

While the allocated memory is few time lesser, it's strange that the allocated memory after few config reloads is 5 times bigger than the initial.

**Comment by bryancall** [comment]
@brbzull0 Is going to take a look at this

**Comment by pbchou** [comment]
Is there any status update on this issue? We just discovered this issue. We are migrating from 7.1.4 (no issue) to 9.1.1 (has issue). This would likely be a blocker for us since testing with a production-like remap config caused ~ 1GB memory increase on each config reload.

**Comment by brbzull0** [comment]
Have you got this very same issue with 9.1? which OpenSSL version are you using?.
Thanks.

**Comment by pbchou** [comment]
@brbzull0 -- Thanks for responding. We think that this issue might be due to a memory leak in the Lua plugin. I will open another issue and work with @shukitchan on it. Thanks.

**Comment by bryancall** [comment]
This issue appears to be resolved / no longer relevant. Closing.

If this is still an issue, please reopen or file a new issue with reproduction steps.
