### ISSUE TITLE
ATS 7.1.0 origins failover problem

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#4776]
ats always retry  dead origins even some healthy origins are still available.

I want to achieve the goal that:
after two failed attempts to connect to the origin, the failed origin will be marked down for 600 seconds, no more requests will go to that origin ( some other healthy origins available) , but from my test, requests still go to the dead origin...

this is not a problem when i use ats v6.x，

following is my configs:
----------------------------------------------
proxy.config.hostdb.strict_round_robin: 1   #enable strict round robin
proxy.config.http.connect_attempts_max_retries: 2  #connect to origin try twice
proxy.config.http.connect_attempts_timeout: 10  #timeout in 10 seconds
proxy.config.http.connect_attempts_max_retries_dead_server: 0 #don't try the dead server
proxy.config.http.connect_attempts_rr_retries: 1 # try rr origin immedialy when first attempt failed
proxy.config.http.down_server.cache_time: 600  #requests should not go to dead server for 600 seconds
proxy.config.http.down_server.abort_threshold: 10 #i don't what it mean

--------------
test against latest v7.1.5 release, the problem still exists!

**Comment by esmq2092** [comment]
i have 3 round robin origins for a site, tww of my origins go down, ats mark the two servers down, but still proxy requests to them 。。。

**Comment by mingzym** [comment]
proxy.config.hostdb.strict_round_robin set to 0 and re-run the test

**Comment by mingzym** [comment]
and @oknet point me out that a bugfix on origin fail over is fixed and backport to 7.1.x, PR 1274, please use the latest 7.1.x to re-do the test.

**Comment by esmq2092** [comment]
test against latest 7.1.x (7.1.5), the problem still exists!

1) multiple origins fail over with hostdb.strict_round_robin，it once has problem, but fixed in v6.x release,

2) i think the regression has something to do with http.connect_attempts_rr_retries，
this is a new config enable ats to retry other origin immedialy when first attemp failed.

**Comment by esmq2092** [comment]
for i don't have c++17 environment, i patch v7.1.5 with #4810 ( https://github.com/apache/trafficserver/pull/4810 ),


after testing, it turns out the bug had fixed now

在 2019-01-16 15:23:55，"scw00" <notifications@github.com> 写道：


Before the test. You need to make sure your TTL of your DNS entry is larger enough.
