### ISSUE TITLE
Intermittent autest failure on client_context_dump

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5671]
Recently, I saw some intermittent failure like below on autest of GitHub Pull Request Builder.

```
Test: client_context_dump: Failed
    File: client_context_dump.test.py
    Directory: /var/jenkins/workspace/autest-github/src/tests/gold_tests/pluginTest/client_context_dump
   file /var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log : Checking that file "/var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log" exists - Passed
      Reason: File "/var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log" exists
   file /var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log : Checking that /var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log matches gold/client_context_dump.gold - Failed
      Reason: File differences
       Gold File : /var/jenkins/workspace/autest-github/src/tests/gold_tests/pluginTest/client_context_dump/gold/client_context_dump.gold
       Data File : /var/tmp/ausb-5670.10287/client_context_dump/ts/log/client_context_dump.log
         20190624.20h01m51s LookupName: :/var/tmp/ausb-5670.10287/client_context_dump/ts/etc/trafficserver:/var/tmp/ausb-5670.10287/client_context_dump/ts/ssl/one.com.pem:, Subject: CN=one.com,O=Apache,L=Champaign,ST=Illinois,C=US. SAN: . Serial: . NotAfter: May 22 18:17:04 2020 GMT.
         20190624.20h01m51s LookupName: :/var/tmp/ausb-5670.10287/client_context_dump/ts/etc/trafficserver:/var/tmp/ausb-5670.10287/client_context_dump/ts/ssl/two.com.pem:, Subject: C=US,ST=Illinois,L=Champaign,OU=Two,O=Apache,emailAddress=ssl@two.com,CN=two.com. SAN: . Serial: . NotAfter: Jun 21 20:39:43 2019 GMT.
       - ``LookupName:``one.com.pem:, Subject: CN=one.com,O=Apache,L=Champaign,ST=Illinois,C=US. SAN: . Serial: . NotAfter: May 22 18:17:04 2020 GMT.
```

https://ci.trafficserver.apache.org/job/autest-github/10287/console

**Comment by dragon512** [comment]
@macisasandwich added a patch to the test that should address some ssl issues that have caused random failures. I think this is fixed. If not make a new one issue

**Comment by masaori335** [comment]
The test still fails intermittently.
```
Test: client_context_dump: Failed
    File: client_context_dump.test.py
    Directory: /var/jenkins/workspace/autest-github/src/tests/gold_tests/pluginTest/client_context_dump
   file /var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log : Checking that file "/var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log" exists - Passed
      Reason: File "/var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log" exists
   file /var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log : Checking that /var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log matches gold/client_context_dump.gold - Failed
      Reason: File differences
       Gold File : /var/jenkins/workspace/autest-github/src/tests/gold_tests/pluginTest/client_context_dump/gold/client_context_dump.gold
       Data File : /var/tmp/ausb-5745.10530/client_context_dump/ts/log/client_context_dump.log
         20190725.17h27m00s LookupName: :/var/tmp/ausb-5745.10530/client_context_dump/ts/etc/trafficserver:/var/tmp/ausb-5745.10530/client_context_dump/ts/ssl/one.com.pem:, Subject: CN=one.com,O=Apache,L=Champaign,ST=Illinois,C=US. SAN: . Serial: . NotAfter: May 22 18:17:04 2020 GMT.
         20190725.17h27m00s LookupName: :/var/tmp/ausb-5745.10530/client_context_dump/ts/etc/trafficserver:/var/tmp/ausb-5745.10530/client_context_dump/ts/ssl/two.com.pem:, Subject: C=US,ST=Illinois,L=Champaign,OU=Two,O=Apache,emailAddress=ssl@two.com,CN=two.com. SAN: . Serial: . NotAfter: Jun 21 20:39:43 2019 GMT.
       - ``LookupName:``one.com.pem:, Subject: CN=one.com,O=Apache,L=Champaign,ST=Illinois,C=US. SAN: . Serial: . NotAfter: May 22 18:17:04 2020 GMT.
```
https://ci.trafficserver.apache.org/job/autest-github/10530/console

**Comment by sudheerv** [comment]
If it helps to have additional data points, I noticed this test fail a few times too and automatically succeed with a rerun. 

For example,

https://ci.trafficserver.apache.org/job/autest-github/10570/

**Comment by masaori335** [comment]
#5828 fixed this failure.
